//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHSHQ.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int NumberOfRetry {
            get {
                return ((int)(this["NumberOfRetry"]));
            }
            set {
                this["NumberOfRetry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LOCAL")]
        public string DBBackupType {
            get {
                return ((string)(this["DBBackupType"]));
            }
            set {
                this["DBBackupType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string ServiceServerIP {
            get {
                return ((string)(this["ServiceServerIP"]));
            }
            set {
                this["ServiceServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ServiceLocal {
            get {
                return ((bool)(this["ServiceLocal"]));
            }
            set {
                this["ServiceLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.248.252.243")]
        public string UHFReaderIP {
            get {
                return ((string)(this["UHFReaderIP"]));
            }
            set {
                this["UHFReaderIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.248.252.201")]
        public string MISCReaderIP {
            get {
                return ((string)(this["MISCReaderIP"]));
            }
            set {
                this["MISCReaderIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7777")]
        public string MISCReaderPort {
            get {
                return ((string)(this["MISCReaderPort"]));
            }
            set {
                this["MISCReaderPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string HumpyDBUserName {
            get {
                return ((string)(this["HumpyDBUserName"]));
            }
            set {
                this["HumpyDBUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int HumpyViewerTimeout_s {
            get {
                return ((int)(this["HumpyViewerTimeout_s"]));
            }
            set {
                this["HumpyViewerTimeout_s"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public float Humpy_TagReadSensitivity_ms {
            get {
                return ((float)(this["Humpy_TagReadSensitivity_ms"]));
            }
            set {
                this["Humpy_TagReadSensitivity_ms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public float Humpy_TagINsensitivity_ms {
            get {
                return ((float)(this["Humpy_TagINsensitivity_ms"]));
            }
            set {
                this["Humpy_TagINsensitivity_ms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HumpyDBSQLInstanceName {
            get {
                return ((string)(this["HumpyDBSQLInstanceName"]));
            }
            set {
                this["HumpyDBSQLInstanceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CraneGroup1")]
        public string PortalUpdate_CraneGroupName1 {
            get {
                return ((string)(this["PortalUpdate_CraneGroupName1"]));
            }
            set {
                this["PortalUpdate_CraneGroupName1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CraneGroup2")]
        public string PortalUpdate_CraneGroupName2 {
            get {
                return ((string)(this["PortalUpdate_CraneGroupName2"]));
            }
            set {
                this["PortalUpdate_CraneGroupName2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CraneGroup3")]
        public string PortalUpdate_CraneGroupName3 {
            get {
                return ((string)(this["PortalUpdate_CraneGroupName3"]));
            }
            set {
                this["PortalUpdate_CraneGroupName3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CraneGroup4")]
        public string PortalUpdate_CraneGroupName4 {
            get {
                return ((string)(this["PortalUpdate_CraneGroupName4"]));
            }
            set {
                this["PortalUpdate_CraneGroupName4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CraneGroup5")]
        public string PortalUpdate_CraneGroupName5 {
            get {
                return ((string)(this["PortalUpdate_CraneGroupName5"]));
            }
            set {
                this["PortalUpdate_CraneGroupName5"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=HQDB;Persist Security Info=True;User ID=sa;" +
            "Password=p@ssw0rd")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p@ssw0rd")]
        public string HumpyDBPassword {
            get {
                return ((string)(this["HumpyDBPassword"]));
            }
            set {
                this["HumpyDBPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SmartHumpy")]
        public string HumpyDBName {
            get {
                return ((string)(this["HumpyDBName"]));
            }
            set {
                this["HumpyDBName"] = value;
            }
        }
    }
}
